"""
Defines the shared AgentState TypedDict used across all LangGraph nodes.
All agents read from and write to this single shared state object.
"""
from typing import Annotated, TypedDict

from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """
    The single source of truth shared across all agents in the graph.

    LangGraph will merge updates from each node into this state object.
    The `add_messages` annotation on `messages` ensures that new messages
    are appended to the list rather than overwriting it.
    """

    # --- Conversation ---
    # Full conversation history; new messages are appended via add_messages.
    messages: Annotated[list, add_messages]
    # The current raw question from the user.
    question: str

    # --- Ingestion ---
    # Absolute path to the uploaded PDF file.
    pdf_path: str | None
    # Flag indicating whether the PDF has been processed and indexed.
    is_ingested: bool
    # The Chroma collection name associated with the current paper.
    collection_name: str | None

    # --- Retrieval ---
    # The question rewritten for better vector search performance.
    rewritten_query: str | None
    # The top-k text chunks retrieved from the vector store.
    retrieved_chunks: list[str]

    # --- Synthesis ---
    # The final answer generated by the LLM.
    final_answer: str | None
    # Source citations extracted from the generated answer.
    citations: list[str]

    # --- Routing ---
    # Signals to the graph which agent node to activate next.
    next_agent: str
